scsi: ufs-qcom: Adapt to cpumasks change
Build fails after commit [1], because it did not modify this driver to be
adapted to the new atomic API.

../drivers/scsi/ufs/ufs-qcom.c:1836:42: error: assigning to 'atomic_t' from incompatible type 'cpumask_t' (aka 'struct cpumask')
 1836 |                 host->pm_qos.groups[i].req.cpus_affine =
      |                                                        ^
 1837 |                         host->pm_qos.groups[i].mask;
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

[1] 1f1e2c8fa4ca17e5b9c4d0be8f168879536996b7 "qos: Replace cpumasks with atomic bitwise operations"

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>